{
	u'5177': {'src': u'/images/cms/familiar/art/5177.png', 'loyalty': u'Awakened', 'id': u'5177', 'name': u'Greenroot Janustrap'},
    u'1144': {'src': u'/images/cms/familiar/art/1144.png', 'loyalty': u'Awakened', 'id': u'1144', 'name': u"Death's-Head Stag"},
    u'1145': {'src': u'/images/cms/familiar/art/1145.png', 'loyalty': u'Awakened', 'id': u'1145', 'name': u'Crimson Emperor'},
    u'14677': {'src': u'/images/cms/familiar/art/14677.png', 'loyalty': u'Wary', 'id': u'14677', 'name': u'Granite Guardian'},
    u'760': {'src': u'/images/cms/familiar/art/760_gray.png', 'loyalty': u'Locked', 'id': u'760', 'name': u'Cog Frog'},
    u'1149': {'src': u'/images/cms/familiar/art/1149.png', 'loyalty': u'Relaxed', 'id': u'1149', 'name': u'Bamboo Phytocat'},
    u'1449': {'src': u'/images/cms/familiar/art/1449.png', 'loyalty': u'Awakened', 'id': u'1449', 'name': u'Southmarsh Podid'},
    u'14570': {'src': u'/images/cms/familiar/art/14570_gray.png', 'loyalty': u'Locked', 'id': u'14570', 'name': u'Swiftfoot Slayer'},
    u'1035': {'src': u'/images/cms/familiar/art/1035.png', 'loyalty': u'Awakened', 'id': u'1035', 'name': u'Red-Breasted Hainu'},
    u'3327': {'src': u'/images/cms/familiar/art/3327_gray.png', 'loyalty': u'Locked', 'id': u'3327', 'name': u'Water Sprite'},
    u'339': {'src': u'/images/cms/familiar/art/339.png', 'loyalty': u'Awakened', 'id': u'339', 'name': u'Leafy Moth'},
    u'2917': {'src': u'/images/cms/familiar/art/2917_gray.png', 'loyalty': u'Locked', 'id': u'2917', 'name': u'Shadow Sprite'},
    u'610': {'src': u'/images/cms/familiar/art/610.png', 'loyalty': u'Awakened', 'id': u'610', 'name': u'Shale Thresher'},
    u'1222': {'src': u'/images/cms/familiar/art/1222_gray.png', 'loyalty': u'Locked', 'id': u'1222', 'name': u'Coarsefur Yeti'},
    u'6340': {'src': u'/images/cms/familiar/art/6340.png', 'loyalty': u'Awakened', 'id': u'6340', 'name': u'Mesacliff Harpy'},
    u'669': {'src': u'/images/cms/familiar/art/669.png', 'loyalty': u'Awakened', 'id': u'669', 'name': u'Frostbite Hummingbird'},
    u'4679': {'src': u'/images/cms/familiar/art/4679_gray.png', 'loyalty': u'Locked', 'id': u'4679', 'name': u'Chocolate Ferret'},
    u'12522': {'src': u'/images/cms/familiar/art/12522.png', 'loyalty': u'Relaxed', 'id': u'12522', 'name': u'Searing Jackalope'},
    u'13085': {'src': u'/images/cms/familiar/art/13085.png', 'loyalty': u'Relaxed', 'id': u'13085', 'name': u'Juvenile Starsweeper'},
    u'7596': {'src': u'/images/cms/familiar/art/7596.png', 'loyalty': u'Relaxed', 'id': u'7596', 'name': u'Scrapmetal Tracker'},
    u'3120': {'src': u'/images/cms/familiar/art/3120.png', 'loyalty': u'Awakened', 'id': u'3120', 'name': u'Gaseous Megashrimp'},
    u'7594': {'src': u'/images/cms/familiar/art/7594_gray.png', 'loyalty': u'Locked', 'id': u'7594', 'name': u'Frost Delver'},
    u'7593': {'src': u'/images/cms/familiar/art/7593.png', 'loyalty': u'Awakened', 'id': u'7593', 'name': u'Coppercoil Creeper'},
    u'7592': {'src': u'/images/cms/familiar/art/7592.png', 'loyalty': u'Awakened', 'id': u'7592', 'name': u'Construction Mith'},
    u'7591': {'src': u'/images/cms/familiar/art/7591.png', 'loyalty': u'Awakened', 'id': u'7591', 'name': u'Black Iron Creeper'},
    u'407': {'src': u'/images/cms/familiar/art/407.png', 'loyalty': u'Awakened', 'id': u'407', 'name': u'Shadow Serpent'},
    u'819': {'src': u'/images/cms/familiar/art/819.png', 'loyalty': u'Awakened', 'id': u'819', 'name': u'Iridescent Scaleback'},
    u'405': {'src': u'/images/cms/familiar/art/405.png', 'loyalty': u'Awakened', 'id': u'405', 'name': u'Baku'},
    u'404': {'src': u'/images/cms/familiar/art/404.png', 'loyalty': u'Awakened', 'id': u'404', 'name': u'Dappled Seal'},
    u'340': {'src': u'/images/cms/familiar/art/340.png', 'loyalty': u'Awakened', 'id': u'340', 'name': u'Cockatrice'},
    u'2151': {'src': u'/images/cms/familiar/art/2151_gray.png', 'loyalty': u'Locked', 'id': u'2151', 'name': u'Earth Sprite'},
    u'342': {'src': u'/images/cms/familiar/art/342.png', 'loyalty': u'Awakened', 'id': u'342', 'name': u'Celestial Antelope'},
    u'343': {'src': u'/images/cms/familiar/art/343.png', 'loyalty': u'Relaxed', 'id': u'343', 'name': u'Trick of the Light'},
    u'7698': {'src': u'/images/cms/familiar/art/7698.png', 'loyalty': u'Relaxed', 'id': u'7698', 'name': u'Ectoplasmime'},
    u'10669': {'src': u'/images/cms/familiar/art/10669.png', 'loyalty': u'Relaxed', 'id': u'10669', 'name': u'Blue Vein Pansy'},
    u'409': {'src': u'/images/cms/familiar/art/409.png', 'loyalty': u'Awakened', 'id': u'409', 'name': u'Silver Springbok'},
    u'1673': {'src': u'/images/cms/familiar/art/1673.png', 'loyalty': u'Awakened', 'id': u'1673', 'name': u'Poisonous Toridae'},
    u'5178': {'src': u'/images/cms/familiar/art/5178.png', 'loyalty': u'Awakened', 'id': u'5178', 'name': u'Janustrap'},
    u'1313': {'src': u'/images/cms/familiar/art/1313_gray.png', 'loyalty': u'Locked', 'id': u'1313', 'name': u'Red-Footed Akirbeak'},
    u'1671': {'src': u'/images/cms/familiar/art/1671_gray.png', 'loyalty': u'Locked', 'id': u'1671', 'name': u'Spined Cobra'},
    u'599': {'src': u'/images/cms/familiar/art/599.png', 'loyalty': u'Awakened', 'id': u'599', 'name': u'Wildwood Owl'},
    u'7597': {'src': u'/images/cms/familiar/art/7597.png', 'loyalty': u'Relaxed', 'id': u'7597', 'name': u'Sentinel Mith'},
    u'4880': {'src': u'/images/cms/familiar/art/4880.png', 'loyalty': u'Relaxed', 'id': u'4880', 'name': u'Snowsquall Floracat'},
    u'4881': {'src': u'/images/cms/familiar/art/4881.png', 'loyalty': u'Relaxed', 'id': u'4881', 'name': u'Harvest Floracat'},
    u'4882': {'src': u'/images/cms/familiar/art/4882.png', 'loyalty': u'Awakened', 'id': u'4882', 'name': u'Velvet Floracat'},
    u'10537': {'src': u'/images/cms/familiar/art/10537.png', 'loyalty': u'Awakened', 'id': u'10537', 'name': u'Timber Tender'},
    u'670': {'src': u'/images/cms/familiar/art/670_gray.png', 'loyalty': u'Locked', 'id': u'670', 'name': u'Black-wing Hummingbird'},
    u'4885': {'src': u'/images/cms/familiar/art/4885.png', 'loyalty': u'Awakened', 'id': u'4885', 'name': u'Colorburst Buttersnake'},
    u'1795': {'src': u'/images/cms/familiar/art/1795.png', 'loyalty': u'Awakened', 'id': u'1795', 'name': u'Blackwing Croaker'},
    u'4887': {'src': u'/images/cms/familiar/art/4887.png', 'loyalty': u'Awakened', 'id': u'4887', 'name': u'Mimic Buttersnake'},
    u'10884': {'src': u'/images/cms/familiar/art/10884.png', 'loyalty': u'Awakened', 'id': u'10884', 'name': u'Cheerful Residue'},
    u'10885': {'src': u'/images/cms/familiar/art/10885.png', 'loyalty': u'Awakened', 'id': u'10885', 'name': u'Shiny Residue'},
    u'10886': {'src': u'/images/cms/familiar/art/10886.png', 'loyalty': u'Awakened', 'id': u'10886', 'name': u'Leftover Residue'},
    u'10887': {'src': u'/images/cms/familiar/art/10887.png', 'loyalty': u'Awakened', 'id': u'10887', 'name': u'Sentient Alloy'},
    u'6337': {'src': u'/images/cms/familiar/art/6337.png', 'loyalty': u'Awakened', 'id': u'6337', 'name': u'Wintermane Bowman'},
    u'420': {'src': u'/images/cms/familiar/art/420.png', 'loyalty': u'Awakened', 'id': u'420', 'name': u'Tengu'},
    u'5511': {'src': u'/images/cms/familiar/art/5511.png', 'loyalty': u'Awakened', 'id': u'5511', 'name': u'Magma Embear'},
    u'6715': {'src': u'/images/cms/familiar/art/6715.png', 'loyalty': u'Awakened', 'id': u'6715', 'name': u'Graveyard Guardian'},
    u'3643': {'src': u'/images/cms/familiar/art/3643.png', 'loyalty': u'Inquisitive', 'id': u'3643', 'name': u'Nature Sprite'},
    u'7883': {'src': u'/images/cms/familiar/art/7883_gray.png', 'loyalty': u'Locked', 'id': u'7883', 'name': u'Wave Sweeper'},
    u'9669': {'src': u'/images/cms/familiar/art/9669_gray.png', 'loyalty': u'Locked', 'id': u'9669', 'name': u'Goliath Mountain Beetle'},
    u'9668': {'src': u'/images/cms/familiar/art/9668_gray.png', 'loyalty': u'Locked', 'id': u'9668', 'name': u'Tufted Leaf Beetle'},
    u'3148': {'src': u'/images/cms/familiar/art/3148_gray.png', 'loyalty': u'Locked', 'id': u'3148', 'name': u'Wind Sprite'},
    u'7882': {'src': u'/images/cms/familiar/art/7882.png', 'loyalty': u'Awakened', 'id': u'7882', 'name': u'Mantarune'},
    u'11219': {'src': u'/images/cms/familiar/art/11219.png', 'loyalty': u'Awakened', 'id': u'11219', 'name': u'Sunbeam Soldier'},
    u'11679': {'src': u'/images/cms/familiar/art/11679.png', 'loyalty': u'Relaxed', 'id': u'11679', 'name': u'Depin'},
    u'7602': {'src': u'/images/cms/familiar/art/7602.png', 'loyalty': u'Awakened', 'id': u'7602', 'name': u'Swift Volt'},
    u'7601': {'src': u'/images/cms/familiar/art/7601.png', 'loyalty': u'Awakened', 'id': u'7601', 'name': u'Swift Lumen'},
    u'10874': {'src': u'/images/cms/familiar/art/10874.png', 'loyalty': u'Awakened', 'id': u'10874', 'name': u'Loga'},
    u'379': {'src': u'/images/cms/familiar/art/379.png', 'loyalty': u'Awakened', 'id': u'379', 'name': u'Cursed Bat'},
    u'415': {'src': u'/images/cms/familiar/art/415.png', 'loyalty': u'Relaxed', 'id': u'415', 'name': u'Dreameater'},
    u'2394': {'src': u'/images/cms/familiar/art/2394.png', 'loyalty': u'Relaxed', 'id': u'2394', 'name': u'Bumble'},
    u'417': {'src': u'/images/cms/familiar/art/417.png', 'loyalty': u'Awakened', 'id': u'417', 'name': u'Dwarf Truffle'},
    u'410': {'src': u'/images/cms/familiar/art/410.png', 'loyalty': u'Awakened', 'id': u'410', 'name': u'Runic Bat'},
    u'2393': {'src': u'/images/cms/familiar/art/2393.png', 'loyalty': u'Relaxed', 'id': u'2393', 'name': u'Coral Carpenter'},
    u'412': {'src': u'/images/cms/familiar/art/412.png', 'loyalty': u'Loyal', 'id': u'412', 'name': u'Rainbow Sprite'},
    u'2258': {'src': u'/images/cms/familiar/art/2258.png', 'loyalty': u'Companion', 'id': u'2258', 'name': u'Fungalhoof Qiriq'},
    u'408': {'src': u'/images/cms/familiar/art/408.png', 'loyalty': u'Awakened', 'id': u'408', 'name': u'Ruby Webwing'},
    u'373': {'src': u'/images/cms/familiar/art/373.png', 'loyalty': u'Awakened', 'id': u'373', 'name': u'Storm Seeker'},
    u'372': {'src': u'/images/cms/familiar/art/372.png', 'loyalty': u'Awakened', 'id': u'372', 'name': u'Death Seeker'},
    u'375': {'src': u'/images/cms/familiar/art/375.png', 'loyalty': u'Awakened', 'id': u'375', 'name': u'Hedgehog'},
    u'374': {'src': u'/images/cms/familiar/art/374_gray.png', 'loyalty': u'Locked', 'id': u'374', 'name': u'Darktouched Chimera'},
    u'377': {'src': u'/images/cms/familiar/art/377.png', 'loyalty': u'Awakened', 'id': u'377', 'name': u'Emerald Webwing'},
    u'376': {'src': u'/images/cms/familiar/art/376.png', 'loyalty': u'Awakened', 'id': u'376', 'name': u'Amaranth Moth'},
    u'591': {'src': u'/images/cms/familiar/art/591_gray.png', 'loyalty': u'Locked', 'id': u'591', 'name': u'Boolean'},
    u'593': {'src': u'/images/cms/familiar/art/593.png', 'loyalty': u'Awakened', 'id': u'593', 'name': u'Hati'},
    u'592': {'src': u'/images/cms/familiar/art/592.png', 'loyalty': u'Awakened', 'id': u'592', 'name': u'Sk\xf6ll'},
    u'595': {'src': u'/images/cms/familiar/art/595.png', 'loyalty': u'Awakened', 'id': u'595', 'name': u'Peacock Firebird'},
    u'416': {'src': u'/images/cms/familiar/art/416.png', 'loyalty': u'Awakened', 'id': u'416', 'name': u'Ethereal Trickster'},
    u'597': {'src': u'/images/cms/familiar/art/597.png', 'loyalty': u'Awakened', 'id': u'597', 'name': u'Blooming Strangler'},
    u'596': {'src': u'/images/cms/familiar/art/596.png', 'loyalty': u'Awakened', 'id': u'596', 'name': u'Strangler'},
    u'982': {'src': u'/images/cms/familiar/art/982_gray.png', 'loyalty': u'Locked', 'id': u'982', 'name': u'Lightning Sprite'},
    u'598': {'src': u'/images/cms/familiar/art/598.png', 'loyalty': u'Awakened', 'id': u'598', 'name': u'Sakura Owl'},
    u'2073': {'src': u'/images/cms/familiar/art/2073.png', 'loyalty': u'Awakened', 'id': u'2073', 'name': u'Spotted Pukasloth'},
    u'987': {'src': u'/images/cms/familiar/art/987.png', 'loyalty': u'Awakened', 'id': u'987', 'name': u'Black Wolf'},
    u'10233': {'src': u'/images/cms/familiar/art/10233_gray.png', 'loyalty': u'Locked', 'id': u'10233', 'name': u'Goldenbeast'},
    u'10232': {'src': u'/images/cms/familiar/art/10232.png', 'loyalty': u'Awakened', 'id': u'10232', 'name': u'Manticore Screamer'},
    u'10231': {'src': u'/images/cms/familiar/art/10231_gray.png', 'loyalty': u'Locked', 'id': u'10231', 'name': u'Overcharged Silverbeast'},
    u'418': {'src': u'/images/cms/familiar/art/418.png', 'loyalty': u'Awakened', 'id': u'418', 'name': u'Opheodrys Serthis'},
    u'1480': {'src': u'/images/cms/familiar/art/1480.png', 'loyalty': u'Awakened', 'id': u'1480', 'name': u'Venerable Shalebuck'},
    u'11148': {'src': u'/images/cms/familiar/art/11148.png', 'loyalty': u'Companion', 'id': u'11148', 'name': u'Mantled Foo'},
    u'13429': {'src': u'/images/cms/familiar/art/13429.png', 'loyalty': u'Relaxed', 'id': u'13429', 'name': u'Crystalplate Stinger'},
    u'10234': {'src': u'/images/cms/familiar/art/10234.png', 'loyalty': u'Awakened', 'id': u'10234', 'name': u'Clown Hippocampus'},
    u'13427': {'src': u'/images/cms/familiar/art/13427.png', 'loyalty': u'Inquisitive', 'id': u'13427', 'name': u'Hippalectryon'},
    u'1929': {'src': u'/images/cms/familiar/art/1929.png', 'loyalty': u'Relaxed', 'id': u'1929', 'name': u'Mistwatch Shellion'},
    u'13425': {'src': u'/images/cms/familiar/art/13425.png', 'loyalty': u'Relaxed', 'id': u'13425', 'name': u'Rhodochrosite Crane'},
    u'13424': {'src': u'/images/cms/familiar/art/13424.png', 'loyalty': u'Companion', 'id': u'13424', 'name': u'Sparkling Stinger'},
    u'4354': {'src': u'/images/cms/familiar/art/4354.png', 'loyalty': u'Awakened', 'id': u'4354', 'name': u'Maren Warrior'},
    u'8320': {'src': u'/images/cms/familiar/art/8320.png', 'loyalty': u'Awakened', 'id': u'8320', 'name': u'Roundhorn Melprin'},
    u'13421': {'src': u'/images/cms/familiar/art/13421.png', 'loyalty': u'Relaxed', 'id': u'13421', 'name': u'Maren Warlock'},
    u'414': {'src': u'/images/cms/familiar/art/414.png', 'loyalty': u'Relaxed', 'id': u'414', 'name': u'Greater Sandstrike'},
    u'2781': {'src': u'/images/cms/familiar/art/2781.png', 'loyalty': u'Relaxed', 'id': u'2781', 'name': u'Brush Dodo'},
    u'2780': {'src': u'/images/cms/familiar/art/2780.png', 'loyalty': u'Awakened', 'id': u'2780', 'name': u'Dodo'},
    u'4806': {'src': u'/images/cms/familiar/art/4806.png', 'loyalty': u'Awakened', 'id': u'4806', 'name': u'Permafrost Impaler'},
    u'378': {'src': u'/images/cms/familiar/art/378.png', 'loyalty': u'Awakened', 'id': u'378', 'name': u'Ember Mouse'},
    u'13422': {'src': u'/images/cms/familiar/art/13422.png', 'loyalty': u'Relaxed', 'id': u'13422', 'name': u'Windcarve Fugitive'},
    u'11680': {'src': u'/images/cms/familiar/art/11680.png', 'loyalty': u'Awakened', 'id': u'11680', 'name': u'Corrosive Depin'},
    u'799': {'src': u'/images/cms/familiar/art/799.png', 'loyalty': u'Awakened', 'id': u'799', 'name': u'Sunset Lasher'},
    u'14291': {'src': u'/images/cms/familiar/art/14291_gray.png', 'loyalty': u'Locked', 'id': u'14291', 'name': u'Bloodstone Beetle'},
    u'14290': {'src': u'/images/cms/familiar/art/14290_gray.png', 'loyalty': u'Locked', 'id': u'14290', 'name': u'Empress Beetle'},
    u'8968': {'src': u'/images/cms/familiar/art/8968.png', 'loyalty': u'Awakened', 'id': u'8968', 'name': u'Murktooth Bramblekeep'},
    u'919': {'src': u'/images/cms/familiar/art/919_gray.png', 'loyalty': u'Locked', 'id': u'919', 'name': u'Golden Idol'},
    u'421': {'src': u'/images/cms/familiar/art/421.png', 'loyalty': u'Awakened', 'id': u'421', 'name': u'Longneck Skirmisher'},
    u'2072': {'src': u'/images/cms/familiar/art/2072.png', 'loyalty': u'Awakened', 'id': u'2072', 'name': u'Fluted Pukasloth'},
    u'4355': {'src': u'/images/cms/familiar/art/4355.png', 'loyalty': u'Awakened', 'id': u'4355', 'name': u'Octoflyer'},
    u'422': {'src': u'/images/cms/familiar/art/422.png', 'loyalty': u'Awakened', 'id': u'422', 'name': u'Longneck Interloper'},
    u'910': {'src': u'/images/cms/familiar/art/910_gray.png', 'loyalty': u'Locked', 'id': u'910', 'name': u'Bone Fiend'},
    u'360': {'src': u'/images/cms/familiar/art/360_gray.png', 'loyalty': u'Locked', 'id': u'360', 'name': u'Manticore'},
    u'361': {'src': u'/images/cms/familiar/art/361.png', 'loyalty': u'Awakened', 'id': u'361', 'name': u'Chimera'},
    u'2604': {'src': u'/images/cms/familiar/art/2604.png', 'loyalty': u'Awakened', 'id': u'2604', 'name': u'Smoky Bantam Fangar'},
    u'1479': {'src': u'/images/cms/familiar/art/1479.png', 'loyalty': u'Awakened', 'id': u'1479', 'name': u'Shalebuck'},
    u'406': {'src': u'/images/cms/familiar/art/406.png', 'loyalty': u'Awakened', 'id': u'406', 'name': u'Steam Gyre'},
    u'1273': {'src': u'/images/cms/familiar/art/1273.png', 'loyalty': u'Awakened', 'id': u'1273', 'name': u'Snowfall Elk'},
    u'2259': {'src': u'/images/cms/familiar/art/2259.png', 'loyalty': u'Relaxed', 'id': u'2259', 'name': u'Umberhorn Qiriq'},
    u'11666': {'src': u'/images/cms/familiar/art/11666.png', 'loyalty': u'Awakened', 'id': u'11666', 'name': u'Parda'},
    u'11669': {'src': u'/images/cms/familiar/art/11669.png', 'loyalty': u'Inquisitive', 'id': u'11669', 'name': u'King Parda'},
    u'14122': {'src': u'/images/cms/familiar/art/14122.png', 'loyalty': u'Inquisitive', 'id': u'14122', 'name': u'Deadland Disciple'},
    u'380': {'src': u'/images/cms/familiar/art/380.png', 'loyalty': u'Awakened', 'id': u'380', 'name': u'Cumulus Seal'},
    u'381': {'src': u'/images/cms/familiar/art/381.png', 'loyalty': u'Awakened', 'id': u'381', 'name': u'Basilisk'},
    u'14442': {'src': u'/images/cms/familiar/art/14442_gray.png', 'loyalty': u'Locked', 'id': u'14442', 'name': u'Grouse Basilisk'},
    u'9488': {'src': u'/images/cms/familiar/art/9488.png', 'loyalty': u'Awakened', 'id': u'9488', 'name': u'Cloudkeeper Herald'},
    u'10228': {'src': u'/images/cms/familiar/art/10228.png', 'loyalty': u'Awakened', 'id': u'10228', 'name': u'Proto Manticore'},
    u'10229': {'src': u'/images/cms/familiar/art/10229.png', 'loyalty': u'Awakened', 'id': u'10229', 'name': u'Ringlet Amphithere'},
    u'13430': {'src': u'/images/cms/familiar/art/13430_gray.png', 'loyalty': u'Locked', 'id': u'13430', 'name': u'Crystalhide Jester'},
    u'13431': {'src': u'/images/cms/familiar/art/13431.png', 'loyalty': u'Companion', 'id': u'13431', 'name': u'Chalcedony Snipper'},
    u'13432': {'src': u'/images/cms/familiar/art/13432.png', 'loyalty': u'Inquisitive', 'id': u'13432', 'name': u'Arctic Hippalectryon'},
    u'13433': {'src': u'/images/cms/familiar/art/13433.png', 'loyalty': u'Inquisitive', 'id': u'13433', 'name': u'Apatite Fisher'},
    u'13434': {'src': u'/images/cms/familiar/art/13434.png', 'loyalty': u'Inquisitive', 'id': u'13434', 'name': u'Amber Gulper'},
    u'13435': {'src': u'/images/cms/familiar/art/13435.png', 'loyalty': u'Relaxed', 'id': u'13435', 'name': u'Almandine Sturgeon'},
    u'13436': {'src': u'/images/cms/familiar/art/13436.png', 'loyalty': u'Relaxed', 'id': u'13436', 'name': u'Clearwater Oracle'},
    u'411': {'src': u'/images/cms/familiar/art/411.png', 'loyalty': u'Awakened', 'id': u'411', 'name': u'Brown River Flight'},
    u'785': {'src': u'/images/cms/familiar/art/785.png', 'loyalty': u'Awakened', 'id': u'785', 'name': u'Fallout Streak'},
    u'7704': {'src': u'/images/cms/familiar/art/7704.png', 'loyalty': u'Awakened', 'id': u'7704', 'name': u'Fungusbearing Phony'},
    u'7705': {'src': u'/images/cms/familiar/art/7705_gray.png', 'loyalty': u'Locked', 'id': u'7705', 'name': u'Jadecarved Decoy'},
    u'7702': {'src': u'/images/cms/familiar/art/7702_gray.png', 'loyalty': u'Locked', 'id': u'7702', 'name': u'Lavaborne Hoax'},
    u'12523': {'src': u'/images/cms/familiar/art/12523.png', 'loyalty': u'Companion', 'id': u'12523', 'name': u'Extinguished Jackalope'},
    u'904': {'src': u'/images/cms/familiar/art/904.png', 'loyalty': u'Inquisitive', 'id': u'904', 'name': u'Fuiran'},
    u'14441': {'src': u'/images/cms/familiar/art/14441_gray.png', 'loyalty': u'Locked', 'id': u'14441', 'name': u'Coral Basilisk'},
    u'11515': {'src': u'/images/cms/familiar/art/11515.png', 'loyalty': u'Awakened', 'id': u'11515', 'name': u'Mossy Cerdae'},
    u'2577': {'src': u'/images/cms/familiar/art/2577_gray.png', 'loyalty': u'Locked', 'id': u'2577', 'name': u'Golden Bantam Fangar'},
    u'4678': {'src': u'/images/cms/familiar/art/4678.png', 'loyalty': u'Awakened', 'id': u'4678', 'name': u'Silver Ferret'},
    u'382': {'src': u'/images/cms/familiar/art/382.png', 'loyalty': u'Awakened', 'id': u'382', 'name': u'Hippogriff'},
    u'10235': {'src': u'/images/cms/familiar/art/10235.png', 'loyalty': u'Awakened', 'id': u'10235', 'name': u'Hippocampus'},
    u'419': {'src': u'/images/cms/familiar/art/419.png', 'loyalty': u'Awakened', 'id': u'419', 'name': u'Carmine Serthis'},
    u'7427': {'src': u'/images/cms/familiar/art/7427.png', 'loyalty': u'Relaxed', 'id': u'7427', 'name': u'Woodland Turkey'},
    u'640': {'src': u'/images/cms/familiar/art/640.png', 'loyalty': u'Awakened', 'id': u'640', 'name': u'Black Dwarf Unicorn'},
    u'643': {'src': u'/images/cms/familiar/art/643_gray.png', 'loyalty': u'Locked', 'id': u'643', 'name': u'Fawn Fox Rat'},
    u'642': {'src': u'/images/cms/familiar/art/642_gray.png', 'loyalty': u'Locked', 'id': u'642', 'name': u'Downy Fox Rat'},
    u'6073': {'src': u'/images/cms/familiar/art/6073.png', 'loyalty': u'Awakened', 'id': u'6073', 'name': u'Hibernal Starbear'},
    u'10226': {'src': u'/images/cms/familiar/art/10226.png', 'loyalty': u'Loyal', 'id': u'10226', 'name': u'Zalis'},
    u'649': {'src': u'/images/cms/familiar/art/649.png', 'loyalty': u'Awakened', 'id': u'649', 'name': u'Emerald Cave Jewel'},
    u'648': {'src': u'/images/cms/familiar/art/648.png', 'loyalty': u'Awakened', 'id': u'648', 'name': u'Citrine Cave Jewel'},
    u'14288': {'src': u'/images/cms/familiar/art/14288_gray.png', 'loyalty': u'Locked', 'id': u'14288', 'name': u'Seaweed Scavenger'},
    u'14289': {'src': u'/images/cms/familiar/art/14289_gray.png', 'loyalty': u'Locked', 'id': u'14289', 'name': u'Autumn Sea Dragon'},
    u'7595': {'src': u'/images/cms/familiar/art/7595.png', 'loyalty': u'Awakened', 'id': u'7595', 'name': u'Mistral Minion'},
    u'820': {'src': u'/images/cms/familiar/art/820.png', 'loyalty': u'Awakened', 'id': u'820', 'name': u'Scaleback'},
    u'623': {'src': u'/images/cms/familiar/art/623.png', 'loyalty': u'Awakened', 'id': u'623', 'name': u'Stonewatch Harpy'},
    u'622': {'src': u'/images/cms/familiar/art/622.png', 'loyalty': u'Awakened', 'id': u'622', 'name': u'Masked Harpy'},
    u'621': {'src': u'/images/cms/familiar/art/621.png', 'loyalty': u'Awakened', 'id': u'621', 'name': u'Cloud Chaser'},
    u'620': {'src': u'/images/cms/familiar/art/620.png', 'loyalty': u'Awakened', 'id': u'620', 'name': u'Golden Porpoise'},
    u'2590': {'src': u'/images/cms/familiar/art/2590.png', 'loyalty': u'Relaxed', 'id': u'2590', 'name': u'Cardinal Hippogriff'},
    u'2591': {'src': u'/images/cms/familiar/art/2591.png', 'loyalty': u'Awakened', 'id': u'2591', 'name': u'Blue Tang Hippogriff'},
    u'1221': {'src': u'/images/cms/familiar/art/1221.png', 'loyalty': u'Awakened', 'id': u'1221', 'name': u'Hoarfrost Mauler'},
    u'13086': {'src': u'/images/cms/familiar/art/13086.png', 'loyalty': u'Relaxed', 'id': u'13086', 'name': u'Lesser Wisp'},
    u'1779': {'src': u'/images/cms/familiar/art/1779_gray.png', 'loyalty': u'Locked', 'id': u'1779', 'name': u'Arcane Sprite'},
    u'629': {'src': u'/images/cms/familiar/art/629.png', 'loyalty': u'Awakened', 'id': u'629', 'name': u'Crimson Reef Snail'},
    u'628': {'src': u'/images/cms/familiar/art/628.png', 'loyalty': u'Awakened', 'id': u'628', 'name': u'Blue Dragon Reef Snail'},
    u'5197': {'src': u'/images/cms/familiar/art/5197.png', 'loyalty': u'Awakened', 'id': u'5197', 'name': u'Shimmering Xolo'},
    u'12739': {'src': u'/images/cms/familiar/art/12739_gray.png', 'loyalty': u'Locked', 'id': u'12739', 'name': u'Amberwing Waveskimmer'},
    u'989': {'src': u'/images/cms/familiar/art/989.png', 'loyalty': u'Awakened', 'id': u'989', 'name': u'Winter Wolf'},
    u'6604': {'src': u'/images/cms/familiar/art/6604.png', 'loyalty': u'Relaxed', 'id': u'6604', 'name': u'Nephrite Chameleon'},
    u'6605': {'src': u'/images/cms/familiar/art/6605.png', 'loyalty': u'Companion', 'id': u'6605', 'name': u'Corundum Chameleon'},
    u'4349': {'src': u'/images/cms/familiar/art/4349.png', 'loyalty': u'Awakened', 'id': u'4349', 'name': u'Relic Eel'},
    u'4348': {'src': u'/images/cms/familiar/art/4348.png', 'loyalty': u'Awakened', 'id': u'4348', 'name': u'Mammertee'},
    u'4347': {'src': u'/images/cms/familiar/art/4347.png', 'loyalty': u'Awakened', 'id': u'4347', 'name': u'Kelp Tender'},
    u'413': {'src': u'/images/cms/familiar/art/413.png', 'loyalty': u'Relaxed', 'id': u'413', 'name': u'Smoke Gyre'},
    u'4356': {'src': u'/images/cms/familiar/art/4356.png', 'loyalty': u'Awakened', 'id': u'4356', 'name': u'Jeweled Octoflyer'},
    u'14546': {'src': u'/images/cms/familiar/art/14546_gray.png', 'loyalty': u'Locked', 'id': u'14546', 'name': u'Venomblade Assassin'},
    u'594': {'src': u'/images/cms/familiar/art/594_gray.png', 'loyalty': u'Locked', 'id': u'594', 'name': u'Mock Firebird'},
    u'1987': {'src': u'/images/cms/familiar/art/1987_gray.png', 'loyalty': u'Locked', 'id': u'1987', 'name': u'Plague Sprite'},
    u'975': {'src': u'/images/cms/familiar/art/975_gray.png', 'loyalty': u'Locked', 'id': u'975', 'name': u'Light Sprite'},
    u'13241': {'src': u'/images/cms/familiar/art/13241.png', 'loyalty': u'Companion', 'id': u'13241', 'name': u'Stardust Scholar'},
    u'2887': {'src': u'/images/cms/familiar/art/2887.png', 'loyalty': u'Awakened', 'id': u'2887', 'name': u'Rivermouth Flatbill'},
    u'1174': {'src': u'/images/cms/familiar/art/1174.png', 'loyalty': u'Awakened', 'id': u'1174', 'name': u'Renegade Aviar'},
    u'4350': {'src': u'/images/cms/familiar/art/4350.png', 'loyalty': u'Awakened', 'id': u'4350', 'name': u'Abyss Striker'},
    u'2888': {'src': u'/images/cms/familiar/art/2888_gray.png', 'loyalty': u'Locked', 'id': u'2888', 'name': u'Driftwood Baron'},
    u'884': {'src': u'/images/cms/familiar/art/884.png', 'loyalty': u'Awakened', 'id': u'884', 'name': u'Maned Rasa'},
    u'10666': {'src': u'/images/cms/familiar/art/10666.png', 'loyalty': u'Awakened', 'id': u'10666', 'name': u'Barkback Boar'},
    u'4351': {'src': u'/images/cms/familiar/art/4351.png', 'loyalty': u'Awakened', 'id': u'4351', 'name': u'Maren Scout'},
    u'11815': {'src': u'/images/cms/familiar/art/11815.png', 'loyalty': u'Inquisitive', 'id': u'11815', 'name': u'Chromefeather Lookout'},
    u'11816': {'src': u'/images/cms/familiar/art/11816.png', 'loyalty': u'Loyal', 'id': u'11816', 'name': u'Sentry Squawker'},
    u'10667': {'src': u'/images/cms/familiar/art/10667.png', 'loyalty': u'Relaxed', 'id': u'10667', 'name': u'Deadwood Boar'},
    u'4352': {'src': u'/images/cms/familiar/art/4352.png', 'loyalty': u'Awakened', 'id': u'4352', 'name': u'Maren Wavesinger'},
    u'650': {'src': u'/images/cms/familiar/art/650.png', 'loyalty': u'Relaxed', 'id': u'650', 'name': u'Hydra Scorpion'},
    u'651': {'src': u'/images/cms/familiar/art/651.png', 'loyalty': u'Awakened', 'id': u'651', 'name': u'Peacock Scorpion'},
    u'403': {'src': u'/images/cms/familiar/art/403.png', 'loyalty': u'Loyal', 'id': u'403', 'name': u'Everglade Lasher'},
    u'4353': {'src': u'/images/cms/familiar/art/4353.png', 'loyalty': u'Awakened', 'id': u'4353', 'name': u'Maren Ambusher'},
    u'1034': {'src': u'/images/cms/familiar/art/1034.png', 'loyalty': u'Awakened', 'id': u'1034', 'name': u'Hainu'},
    u'341': {'src': u'/images/cms/familiar/art/341.png', 'loyalty': u'Awakened', 'id': u'341', 'name': u'Glowing Pocket Mouse'},
    u'6335': {'src': u'/images/cms/familiar/art/6335.png', 'loyalty': u'Awakened', 'id': u'6335', 'name': u'Raptorik Warrior'},
    u'631': {'src': u'/images/cms/familiar/art/631.png', 'loyalty': u'Relaxed', 'id': u'631', 'name': u'Corpse Cleaner'},
    u'632': {'src': u'/images/cms/familiar/art/632.png', 'loyalty': u'Awakened', 'id': u'632', 'name': u'Crowned Bonepriest'},
    u'635': {'src': u'/images/cms/familiar/art/635_gray.png', 'loyalty': u'Locked', 'id': u'635', 'name': u'Dunhoof Ambassador'},
    u'636': {'src': u'/images/cms/familiar/art/636_gray.png', 'loyalty': u'Locked', 'id': u'636', 'name': u'Dappled Dunhoof'},
    u'637': {'src': u'/images/cms/familiar/art/637.png', 'loyalty': u'Awakened', 'id': u'637', 'name': u'River Muck'},
    u'2420': {'src': u'/images/cms/familiar/art/2420.png', 'loyalty': u'Awakened', 'id': u'2420', 'name': u'Greatshell'},
    u'2421': {'src': u'/images/cms/familiar/art/2421.png', 'loyalty': u'Awakened', 'id': u'2421', 'name': u'Blueridge Greatshell'},
    u'786': {'src': u'/images/cms/familiar/art/786.png', 'loyalty': u'Awakened', 'id': u'786', 'name': u'Snow Streak'},
    u'11147': {'src': u'/images/cms/familiar/art/11147.png', 'loyalty': u'Loyal', 'id': u'11147', 'name': u'Tigerblood Foo'},
    u'3070': {'src': u'/images/cms/familiar/art/3070.png', 'loyalty': u'Awakened', 'id': u'3070', 'name': u'Dark-Tufted Sparrowmouse'},
    u'1594': {'src': u'/images/cms/familiar/art/1594_gray.png', 'loyalty': u'Locked', 'id': u'1594', 'name': u'Fire Sprite'},
    u'7599': {'src': u'/images/cms/familiar/art/7599.png', 'loyalty': u'Awakened', 'id': u'7599', 'name': u'Steelhound'},
    u'3175': {'src': u'/images/cms/familiar/art/3175.png', 'loyalty': u'Awakened', 'id': u'3175', 'name': u'Bucktooth Digger'},
    u'3177': {'src': u'/images/cms/familiar/art/3177.png', 'loyalty': u'Awakened', 'id': u'3177', 'name': u'Marbled Jester'},
    u'3176': {'src': u'/images/cms/familiar/art/3176.png', 'loyalty': u'Awakened', 'id': u'3176', 'name': u'Irradiated Astronomer'},
    u'1364': {'src': u'/images/cms/familiar/art/1364.png', 'loyalty': u'Relaxed', 'id': u'1364', 'name': u'Scythe Kamaitachi'},
    u'338': {'src': u'/images/cms/familiar/art/338.png', 'loyalty': u'Awakened', 'id': u'338', 'name': u'Luna Mith'},
    u'7700': {'src': u'/images/cms/familiar/art/7700.png', 'loyalty': u'Awakened', 'id': u'7700', 'name': u'Sundial Imposter'},
    u'9998': {'src': u'/images/cms/familiar/art/9998.png', 'loyalty': u'Awakened', 'id': u'9998', 'name': u'Wavebreak Snarler'},
    u'10668': {'src': u'/images/cms/familiar/art/10668_gray.png', 'loyalty': u'Locked', 'id': u'10668', 'name': u'Orange Blotch Pansy'},
    u'905': {'src': u'/images/cms/familiar/art/905.png', 'loyalty': u'Relaxed', 'id': u'905', 'name': u'Nightsky Fuiran'},
    u'7600': {'src': u'/images/cms/familiar/art/7600_gray.png', 'loyalty': u'Locked', 'id': u'7600', 'name': u'Stone Borer'},
    u'12740': {'src': u'/images/cms/familiar/art/12740_gray.png', 'loyalty': u'Locked', 'id': u'12740', 'name': u'Great Blue Waveskimmer'},
    u'14547': {'src': u'/images/cms/familiar/art/14547_gray.png', 'loyalty': u'Locked', 'id': u'14547', 'name': u'Blueband Duelist'},
    u'7699': {'src': u'/images/cms/familiar/art/7699.png', 'loyalty': u'Relaxed', 'id': u'7699', 'name': u'Jawlocker'},
    u'727': {'src': u'/images/cms/familiar/art/727.png', 'loyalty': u'Awakened', 'id': u'727', 'name': u'GoldThroated Sparrow'},
    u'10230': {'src': u'/images/cms/familiar/art/10230.png', 'loyalty': u'Awakened', 'id': u'10230', 'name': u'Paradise Zalis'},
    u'1450': {'src': u'/images/cms/familiar/art/1450.png', 'loyalty': u'Awakened', 'id': u'1450', 'name': u'Common Podid'},
    u'1672': {'src': u'/images/cms/familiar/art/1672.png', 'loyalty': u'Awakened', 'id': u'1672', 'name': u'Venomous Toridae'},
    u'1101': {'src': u'/images/cms/familiar/art/1101.png', 'loyalty': u'Relaxed', 'id': u'1101', 'name': u'Poultrygeist'},
    u'725': {'src': u'/images/cms/familiar/art/725.png', 'loyalty': u'Awakened', 'id': u'725', 'name': u'Perching Java Sparrow'},
    u'3071': {'src': u'/images/cms/familiar/art/3071.png', 'loyalty': u'Awakened', 'id': u'3071', 'name': u'Yellow-Throated Sparrowmouse'},
    u'1365': {'src': u'/images/cms/familiar/art/1365.png', 'loyalty': u'Awakened', 'id': u'1365', 'name': u'Sickle Kamaitachi'},
    u'883': {'src': u'/images/cms/familiar/art/883.png', 'loyalty': u'Awakened', 'id': u'883', 'name': u'Squall Rasa'},
    u'747': {'src': u'/images/cms/familiar/art/747.png', 'loyalty': u'Inquisitive', 'id': u'747', 'name': u'Ragamouse'},
    u'607': {'src': u'/images/cms/familiar/art/607.png', 'loyalty': u'Awakened', 'id': u'607', 'name': u'Rambra'},
    u'601': {'src': u'/images/cms/familiar/art/601.png', 'loyalty': u'Awakened', 'id': u'601', 'name': u'Red-Winged Owlcat'},
    u'600': {'src': u'/images/cms/familiar/art/600.png', 'loyalty': u'Awakened', 'id': u'600', 'name': u'Banded Owlcat'},
    u'746': {'src': u'/images/cms/familiar/art/746_gray.png', 'loyalty': u'Locked', 'id': u'746', 'name': u'Skycat'},
    u'2623': {'src': u'/images/cms/familiar/art/2623_gray.png', 'loyalty': u'Locked', 'id': u'2623', 'name': u'Ice Sprite'},
    u'748': {'src': u'/images/cms/familiar/art/748.png', 'loyalty': u'Awakened', 'id': u'748', 'name': u'Glossy Duskrat'},
    u'13428': {'src': u'/images/cms/familiar/art/13428_gray.png', 'loyalty': u'Locked', 'id': u'13428', 'name': u'Hawksbill Goliath'},
    u'609': {'src': u'/images/cms/familiar/art/609.png', 'loyalty': u'Awakened', 'id': u'609', 'name': u'Granite Thresher'},
    u'608': {'src': u'/images/cms/familiar/art/608.png', 'loyalty': u'Awakened', 'id': u'608', 'name': u'Zeeba'},
    u'7697': {'src': u'/images/cms/familiar/art/7697.png', 'loyalty': u'Relaxed', 'id': u'7697', 'name': u'Snarling Mimic'},
    u'11510': {'src': u'/images/cms/familiar/art/11510.png', 'loyalty': u'Awakened', 'id': u'11510', 'name': u'Wetland Unicorn'},
    u'11525': {'src': u'/images/cms/familiar/art/11525_gray.png', 'loyalty': u'Locked', 'id': u'11525', 'name': u'Molten Wartoad'},
    u'10227': {'src': u'/images/cms/familiar/art/10227.png', 'loyalty': u'Relaxed', 'id': u'10227', 'name': u'Ultramel Amphithere'},
    u'11522': {'src': u'/images/cms/familiar/art/11522_gray.png', 'loyalty': u'Locked', 'id': u'11522', 'name': u'Wartoad'},
    u'13426': {'src': u'/images/cms/familiar/art/13426.png', 'loyalty': u'Inquisitive', 'id': u'13426', 'name': u'Moonbeam Crayfish'},
    u'8400': {'src': u'/images/cms/familiar/art/8400.png', 'loyalty': u'Awakened', 'id': u'8400', 'name': u'Polarfreeze Defender'},
    u'9226': {'src': u'/images/cms/familiar/art/9226.png', 'loyalty': u'Awakened', 'id': u'9226', 'name': u'Petal Jumper'},
    u'9225': {'src': u'/images/cms/familiar/art/9225.png', 'loyalty': u'Awakened', 'id': u'9225', 'name': u'Budwing Morpho'},
    u'12194': {'src': u'/images/cms/familiar/art/12194_gray.png', 'loyalty': u'Locked', 'id': u'12194', 'name': u'Anomalous Skink'},
    u'12195': {'src': u'/images/cms/familiar/art/12195_gray.png', 'loyalty': u'Locked', 'id': u'12195', 'name': u'Conjoined Skink'},
    u'6341': {'src': u'/images/cms/familiar/art/6341.png', 'loyalty': u'Awakened', 'id': u'6341', 'name': u'Windcarve Harpy'},
    u'357': {'src': u'/images/cms/familiar/art/357.png', 'loyalty': u'Inquisitive', 'id': u'357', 'name': u'Dryad'},
    u'14558': {'src': u'/images/cms/familiar/art/14558_gray.png', 'loyalty': u'Locked', 'id': u'14558', 'name': u'Deepmine Aardvark'},
    u'7703': {'src': u'/images/cms/familiar/art/7703_gray.png', 'loyalty': u'Locked', 'id': u'7703', 'name': u'Slumbering Charlatan'},
    u'4927': {'src': u'/images/cms/familiar/art/4927.png', 'loyalty': u'Awakened', 'id': u'4927', 'name': u'Livewire Grizzly'},
    u'1969': {'src': u'/images/cms/familiar/art/1969.png', 'loyalty': u'Awakened', 'id': u'1969', 'name': u'Spinel Vulstal'},
    u'10759': {'src': u'/images/cms/familiar/art/10759.png', 'loyalty': u'Awakened', 'id': u'10759', 'name': u'Longneck Hunter'},
    u'4001': {'src': u'/images/cms/familiar/art/4001.png', 'loyalty': u'Awakened', 'id': u'4001', 'name': u'Sprangyroo'},
    u'4002': {'src': u'/images/cms/familiar/art/4002.png', 'loyalty': u'Awakened', 'id': u'4002', 'name': u'Charcoal Sprangyroo'},
    u'5196': {'src': u'/images/cms/familiar/art/5196.png', 'loyalty': u'Awakened', 'id': u'5196', 'name': u'Candycane Xolo'},
    u'7328': {'src': u'/images/cms/familiar/art/7328.png', 'loyalty': u'Awakened', 'id': u'7328', 'name': u'Cragbacked Bouldursa'},
    u'355': {'src': u'/images/cms/familiar/art/355_gray.png', 'loyalty': u'Locked', 'id': u'355', 'name': u'Hippojay'},
    u'7701': {'src': u'/images/cms/familiar/art/7701.png', 'loyalty': u'Awakened', 'id': u'7701', 'name': u'Voltspire Intruder'},
    u'10760': {'src': u'/images/cms/familiar/art/10760.png', 'loyalty': u'Awakened', 'id': u'10760', 'name': u'Longneck Wanderer'},
    u'354': {'src': u'/images/cms/familiar/art/354.png', 'loyalty': u'Relaxed', 'id': u'354', 'name': u'Scarlet Flycatcher'},
    u'639': {'src': u'/images/cms/familiar/art/639.png', 'loyalty': u'Awakened', 'id': u'639', 'name': u'Dwarf Unicorn'},
    u'1293': {'src': u'/images/cms/familiar/art/1293.png', 'loyalty': u'Awakened', 'id': u'1293', 'name': u'Sunspot Clouddancer'},
    u'1564': {'src': u'/images/cms/familiar/art/1564.png', 'loyalty': u'Awakened', 'id': u'1564', 'name': u'Psywurm'},
    u'1565': {'src': u'/images/cms/familiar/art/1565.png', 'loyalty': u'Awakened', 'id': u'1565', 'name': u'Brilliant Psywurm'},
    u'1294': {'src': u'/images/cms/familiar/art/1294.png', 'loyalty': u'Awakened', 'id': u'1294', 'name': u'Clouddancer'},
    u'618': {'src': u'/images/cms/familiar/art/618.png', 'loyalty': u'Awakened', 'id': u'618', 'name': u'Bramble Guardian'},
    u'619': {'src': u'/images/cms/familiar/art/619.png', 'loyalty': u'Awakened', 'id': u'619', 'name': u'Parasitic Fungus'},
    u'1173': {'src': u'/images/cms/familiar/art/1173.png', 'loyalty': u'Awakened', 'id': u'1173', 'name': u'Bluemoon Aviar'},
    u'773': {'src': u'/images/cms/familiar/art/773.png', 'loyalty': u'Awakened', 'id': u'773', 'name': u'Warcat Protector'},
    u'772': {'src': u'/images/cms/familiar/art/772.png', 'loyalty': u'Awakened', 'id': u'772', 'name': u'Double-Tailed Warcat'},
    u'612': {'src': u'/images/cms/familiar/art/612.png', 'loyalty': u'Awakened', 'id': u'612', 'name': u'Umbra Wolf'},
    u'4884': {'src': u'/images/cms/familiar/art/4884.png', 'loyalty': u'Awakened', 'id': u'4884', 'name': u'Swallowtail Buttersnake'},
    u'1272': {'src': u'/images/cms/familiar/art/1272.png', 'loyalty': u'Awakened', 'id': u'1272', 'name': u'Elk'},
    u'611': {'src': u'/images/cms/familiar/art/611.png', 'loyalty': u'Inquisitive', 'id': u'611', 'name': u'Gale Wolf'},
    u'616': {'src': u'/images/cms/familiar/art/616.png', 'loyalty': u'Awakened', 'id': u'616', 'name': u'Bluefin Charger'},
    u'617': {'src': u'/images/cms/familiar/art/617.png', 'loyalty': u'Awakened', 'id': u'617', 'name': u'Clown Charger'},
    u'1796': {'src': u'/images/cms/familiar/art/1796.png', 'loyalty': u'Awakened', 'id': u'1796', 'name': u'Heartred Croaker'},
    u'12550': {'src': u'/images/cms/familiar/art/12550.png', 'loyalty': u'Loyal', 'id': u'12550', 'name': u'Molten Marauder'},
    u'1573': {'src': u'/images/cms/familiar/art/1573_gray.png', 'loyalty': u'Locked', 'id': u'1573', 'name': u'Speedy'},
    u'13423': {'src': u'/images/cms/familiar/art/13423.png', 'loyalty': u'Relaxed', 'id': u'13423', 'name': u'Stonewatch Prince'},
    u'4886': {'src': u'/images/cms/familiar/art/4886.png', 'loyalty': u'Awakened', 'id': u'4886', 'name': u'Mottled Buttersnake'},
    u'14560': {'src': u'/images/cms/familiar/art/14560_gray.png', 'loyalty': u'Locked', 'id': u'14560', 'name': u'Peacevine Aardvark'},
    u'1968': {'src': u'/images/cms/familiar/art/1968.png', 'loyalty': u'Awakened', 'id': u'1968', 'name': u'Tourmaline Vulstal'},
    u'8319': {'src': u'/images/cms/familiar/art/8319.png', 'loyalty': u'Awakened', 'id': u'8319', 'name': u'Melprin'},
    u'14569': {'src': u'/images/cms/familiar/art/14569_gray.png', 'loyalty': u'Locked', 'id': u'14569', 'name': u'Centaur Berserker'},
    u'4805': {'src': u'/images/cms/familiar/art/4805.png', 'loyalty': u'Awakened', 'id': u'4805', 'name': u'Nochnyr'},
    u'3782': {'src': u'/images/cms/familiar/art/3782.png', 'loyalty': u'Awakened', 'id': u'3782', 'name': u'Grasslands Trunker'},
    u'3783': {'src': u'/images/cms/familiar/art/3783.png', 'loyalty': u'Awakened', 'id': u'3783', 'name': u'Moordwelling Trunker'},
    u'800': {'src': u'/images/cms/familiar/art/800.png', 'loyalty': u'Awakened', 'id': u'800', 'name': u'Noggle'},
    u'4156': {'src': u'/images/cms/familiar/art/4156.png', 'loyalty': u'Awakened', 'id': u'4156', 'name': u'Sunbeam Ursa'},
    u'359': {'src': u'/images/cms/familiar/art/359.png', 'loyalty': u'Companion', 'id': u'359', 'name': u'Shattered Serpent'},
    u'3119': {'src': u'/images/cms/familiar/art/3119.png', 'loyalty': u'Awakened', 'id': u'3119', 'name': u'Skittering Megashrimp'},
    u'4883': {'src': u'/images/cms/familiar/art/4883.png', 'loyalty': u'Awakened', 'id': u'4883', 'name': u'Tuxedo Floracat'},
    u'7598': {'src': u'/images/cms/familiar/art/7598.png', 'loyalty': u'Companion', 'id': u'7598', 'name': u'Spellbound Golem'},
    u'2782': {'src': u'/images/cms/familiar/art/2782.png', 'loyalty': u'Awakened', 'id': u'2782', 'name': u'Hooded Dodo'},
    u'6339': {'src': u'/images/cms/familiar/art/6339.png', 'loyalty': u'Relaxed', 'id': u'6339', 'name': u'Wintermane Spearman'},
    u'6334': {'src': u'/images/cms/familiar/art/6334.png', 'loyalty': u'Awakened', 'id': u'6334', 'name': u'Blacktalon Striker'},
    u'356': {'src': u'/images/cms/familiar/art/356.png', 'loyalty': u'Awakened', 'id': u'356', 'name': u'Ancient Fungus'},
    u'6336': {'src': u'/images/cms/familiar/art/6336.png', 'loyalty': u'Relaxed', 'id': u'6336', 'name': u'Centaur Archer'},
    u'1578': {'src': u'/images/cms/familiar/art/1578_gray.png', 'loyalty': u'Locked', 'id': u'1578', 'name': u'Maned Cobra'},
    u'353': {'src': u'/images/cms/familiar/art/353.png', 'loyalty': u'Awakened', 'id': u'353', 'name': u'Grey River Flight'},
    u'1363': {'src': u'/images/cms/familiar/art/1363.png', 'loyalty': u'Awakened', 'id': u'1363', 'name': u'Salve Kamaitachi'},
    u'6332': {'src': u'/images/cms/familiar/art/6332.png', 'loyalty': u'Relaxed', 'id': u'6332', 'name': u'Serthis Potionmaster'},
    u'6333': {'src': u'/images/cms/familiar/art/6333.png', 'loyalty': u'Awakened', 'id': u'6333', 'name': u'Serthis Alchemist'},
    u'803': {'src': u'/images/cms/familiar/art/803.png', 'loyalty': u'Awakened', 'id': u'803', 'name': u'Longneck Magi'},
    u'1930': {'src': u'/images/cms/familiar/art/1930.png', 'loyalty': u'Awakened', 'id': u'1930', 'name': u'Shellion'},
    u'804': {'src': u'/images/cms/familiar/art/804.png', 'loyalty': u'Awakened', 'id': u'804', 'name': u'Longneck Mender'},
    u'6338': {'src': u'/images/cms/familiar/art/6338.png', 'loyalty': u'Inquisitive', 'id': u'6338', 'name': u'Painted Centaur'},
    u'11969': {'src': u'/images/cms/familiar/art/11969.png', 'loyalty': u'Awakened', 'id': u'11969', 'name': u'Lightning Lancer'},
    u'638': {'src': u'/images/cms/familiar/art/638.png', 'loyalty': u'Awakened', 'id': u'638', 'name': u'Radioactive Slime'},
    u'358': {'src': u'/images/cms/familiar/art/358.png', 'loyalty': u'Awakened', 'id': u'358', 'name': u'Autumn Dryad'}
}
